sudo: required
services:
        - docker

before_install:
        - docker build -t rysiula/docker-react -f Dockerfile.dev .

script:
        - docker run -it rysiula/docker-react npm run test -- --coverage
