sudo: required
services:
        - docker

befor_install:
        - docker build -t Rysiula/docker-react -f Dockerfile.dev

script:
        - docker run Rysiula/docker-react npm run test -- --coverage
